services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_HOST=${HOST}
            - POSTGRES_USER=${USER}
            - POSTGRES_DB=${DB}
            - POSTGRES_PASSWORD=${PASSWORD}
        container_name: database
        restart: always
